### ISSUE TITLE
NanoHTTPD Exception in Oculus Quest Discord RPC jar

### ISSUE THREAD

**Issue by chr1s-b** [madmagic007/Oculus-Quest-Presence#34]
Hi there,

I've installed the ocrpc.apk successfully onto Sidequest. I ran the installer Oqrpc - Windows.exe.
On double clicking the shortcut Oculus Quest Discord RPC, it did not create a window, so I tried running it from the install directory (`... AppData/Roaming/Oculus Quest Discord RPC`) with the command `java -jar "Oculus Quest Discord RPC.jar"` and it returned this error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: fi/iki/elonen/NanoHTTPD
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.madmagic.oqrpc.source.Main.main(Main.java:24)
Caused by: java.lang.ClassNotFoundException: fi.iki.elonen.NanoHTTPD
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 13 more
```

I am running the latest version of JRE, and this is from downloading the latest release 2.8.1. On a Windows machine of course.
As far as I can tell, it is not my firewall. I don't have any third-party antivirus/firewall and I've tried running it with admin priveleges and Windows firewall disabled.

Any help would be much appreciated, thanks for putting together this project :)

**Comment by michael-r-elp** [comment]
Same issue, I guess only thing that can be done is using the older version, until the newer one is fixed, another thing I noticed is, that the zip file is actually a rar5 file according to 7-zip because it has thrown an warning with, the file can't be opened as zip but rather as rar5

The issue seems to possibly be related to the update to a newer NanoHTTPD version

**Comment by madmagic007** [comment]
Looks like something went wrong in the compilation process. should be an easy fix. i will update the release in a couple minutes

**Comment by madmagic007** [comment]
https://github.com/madmagic007/Oculus-Quest-Presence/releases/tag/2.8.2
If you are using 2.8.1 it should automatically prompt with an update to the 2.8.2 version
